kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: default
spec:
  type: ExternalName
  externalName: prometheus-server.monitoring.svc.cluster.local
  ports:
  - port: 80 #specify the port of service you want to expose 
    targetPort: 80 #port of external service 
---

kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: default
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
  ports:
  - port: 80 #specify the port of service you want to expose 
    targetPort: 80 #port of external service