apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:jdk21
    workingDir: /home/jenkins/agent
  - name: main-worker
    image: mateduard/k8s-kaniko-git:1.2
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
      readOnly: true
  volumes:
  - name: docker-config
    secret:
      secretName: docker-creds
      items:
      - key: .dockerconfigjson
        path: config.json 
      optional: true      # If secret doesn't exist, let jenkins pipeline create it on the worker instead of preventing the worker to start