apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default  # Change to your Jenkins namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
# Pod management
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Pod exec and logs (WebSocket connections)
- apiGroups: [""]
  resources: ["pods/exec", "pods/log", "pods/portforward"]
  verbs: ["create", "get", "list", "watch"]
# Secrets and ConfigMaps
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
# Events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# Nodes (for node selection)
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Persistent Volumes
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Apps resources
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default